theme = "tokyonight_storm"

[editor]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":buffer-next"
S-tab = ":buffer-previous"

S-up = "page_cursor_half_up"
S-down = "page_cursor_half_down"
C-s = ":wa"
"=" = ":format"
x = "select_line_below"
X = "select_line_above"

# Move line down.
C-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# Move line up.
C-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.select]
S-up = "page_cursor_half_up"
S-down = "page_cursor_half_down"

[keys.normal.space]
x = ":buffer-close"
u = ":reset-diff-change"
