theme = "tokyonight_storm"

[editor]
bufferline = "always"
end-of-line-diagnostics = "hint"

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.soft-wrap]
enable = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"=" = ":format"
x = "select_line_below"
X = "select_line_above"
tab = ":buffer-next"
S-tab = ":buffer-previous"
S-up = "page_cursor_half_up"
S-down = "page_cursor_half_down"
C-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-e = [
  ':sh rm -f /tmp/unique-file',
  ":insert-output yazi '%{buffer_name}' --chooser-file=/tmp/unique-file",
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
C-g = [
  ":write-all", 
  ":new", 
  ":insert-output lazygit", 
  ":set mouse false",
  ":set mouse true",
  ":buffer-close!", 
  ":redraw", 
  ":reload-all"
]

[keys.select]
S-up = "page_cursor_half_up"
S-down = "page_cursor_half_down"
C-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[keys.normal.space]
x = ":buffer-close"
u = ":reset-diff-change"
i = ":toggle-option lsp.display-inlay-hints"

[keys.select.space]
u = ":reset-diff-change"

